package migraterun

import (
	"strings"
	"testing"

	"github.com/PhelipeViana/flexberry/internal/config"
	"github.com/PhelipeViana/flexberry/internal/migrategen"
)

func TestCreateTableSQLSupportsAllDialects(t *testing.T) {
	columns := []migrategen.Column{
		{Name: "id", Type: "integer", PrimaryKey: true},
		{Name: "nome", Type: "string"},
	}
	expected := map[string]string{
		"postgres":  "BIGSERIAL",
		"oracle":    "GENERATED BY DEFAULT AS IDENTITY",
		"mysql":     "AUTO_INCREMENT",
		"sqlserver": "IDENTITY(1,1)",
	}
	for dialect, fragment := range expected {
		query, err := createTableSQL(dialect, "public", "pessoas", columns)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(query, fragment) {
			t.Fatalf("%s não contém %q: %s", dialect, fragment, query)
		}
	}
}

func TestQualifiedIdentifiers(t *testing.T) {
	if got := qualified("postgres", "public", "pessoas"); got != `"public"."pessoas"` {
		t.Fatalf("postgres inesperado: %s", got)
	}
	if got := qualified("sqlserver", "dbo", "pessoas"); got != `[dbo].[pessoas]` {
		t.Fatalf("sqlserver inesperado: %s", got)
	}
	if got := qualified("mysql", "", "pessoas"); got != "`pessoas`" {
		t.Fatalf("mysql inesperado: %s", got)
	}
}

func TestAlterAndDropSQL(t *testing.T) {
	column := migrategen.Column{Name: "descricao", Type: "string", Nullable: true}
	postgres := alterColumnSQL("postgres", "public", "produtos", column, nil)
	if len(postgres) != 2 || !strings.Contains(postgres[0], "TYPE VARCHAR(255)") {
		t.Fatalf("alter postgres inesperado: %#v", postgres)
	}
	if got := dropTableSQL("oracle", "APP", "temporarios"); !strings.Contains(got, "CASCADE CONSTRAINTS PURGE") {
		t.Fatalf("drop oracle inesperado: %s", got)
	}
}

func TestOracleIdentifiersAreUppercase(t *testing.T) {
	if got := qualified("oracle", "flexberry", "migrations_flex"); got != `"FLEXBERRY"."MIGRATIONS_FLEX"` {
		t.Fatalf("identificador Oracle inesperado: %s", got)
	}
}

func TestHistoryLocationDoesNotExposeCredentials(t *testing.T) {
	connection := config.Connection{
		Dialect: "postgres",
		URL:     "postgres://user:secret@localhost:5499/flexberry?sslmode=disable",
		Schema:  "public",
	}
	got := historyLocation(connection, "migrations_flex")
	if got != "localhost:5499/flexberry.public.migrations_flex" {
		t.Fatalf("local inesperado: %s", got)
	}
	if strings.Contains(got, "secret") {
		t.Fatal("credencial exposta")
	}
}
