package flexberry

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"time"
)

const FactoryTable = "flexberry_factories"

type Factory struct {
	Name         string
	Mapping      EntityMapping
	Count        int
	Active       bool
	Update       bool
	Dependencies []string
	Connection   string
	Data         func(index int) map[string]any
}

type FactoryResult struct {
	Name      string
	Table     string
	Created   int
	StartedAt time.Time
	EndedAt   time.Time
}

// Link represents a value read from a column populated by another factory.
type Link struct {
	Table  string
	Column string
}

// Vinculo declares that a field reuses a value from a parent table.
func Vinculo(table, column string) Link {
	return Link{Table: table, Column: column}
}

// Clean removes rows generated for the mapped table.
func (factory Factory) Clean(ctx context.Context) error {
	if !validIdentifier(factory.Mapping.Table) {
		return fmt.Errorf("tabela inválida %q", factory.Mapping.Table)
	}
	name := factory.Connection
	if name == "" {
		name = factory.Mapping.Connection
	}
	conn, err := connection(name)
	if err != nil {
		return err
	}
	if _, err := conn.executor.ExecContext(ctx, "DELETE FROM "+factory.Mapping.Table); err != nil {
		return fmt.Errorf("limpar %s: %w", factory.Mapping.Table, err)
	}
	return nil
}

func (factory Factory) Run(ctx context.Context) (FactoryResult, error) {
	result := FactoryResult{Name: factory.Name, Table: factory.Mapping.Table, StartedAt: time.Now()}
	if !factory.Active {
		result.EndedAt = time.Now()
		return result, nil
	}
	if factory.Name == "" || !validIdentifier(factory.Mapping.Table) || factory.Data == nil {
		return result, fmt.Errorf("factory inválida: nome, mapping e Data são obrigatórios")
	}
	if factory.Count < 1 {
		return result, fmt.Errorf("factory %s precisa de Count maior que zero", factory.Name)
	}
	name := factory.Connection
	if name == "" {
		name = factory.Mapping.Connection
	}
	conn, err := connection(name)
	if err != nil {
		return result, err
	}
	if err := ensureFactoryTable(ctx, conn); err != nil {
		return result, err
	}
	if factory.Update {
		if _, err := conn.executor.ExecContext(ctx, "DELETE FROM "+factory.Mapping.Table); err != nil {
			return result, fmt.Errorf("limpar %s: %w", factory.Mapping.Table, err)
		}
	}
	links := make(map[Link][]any)
	for index := 0; index < factory.Count; index++ {
		values, err := resolveFactoryLinks(ctx, conn, factory.Data(index), index, links)
		if err != nil {
			return result, fmt.Errorf("%s: resolver índice %d: %w", factory.Name, index, err)
		}
		if err := insertFactoryData(ctx, conn, factory.Mapping, values); err != nil {
			return result, fmt.Errorf("%s índice %d: %w", factory.Name, index, err)
		}
		result.Created++
	}
	result.EndedAt = time.Now()
	if err := trackFactory(ctx, conn, result); err != nil {
		return result, err
	}
	return result, nil
}

func resolveFactoryLinks(ctx context.Context, conn registeredConnection, values map[string]any, index int, cache map[Link][]any) (map[string]any, error) {
	resolved := make(map[string]any, len(values))
	for column, value := range values {
		link, linked := value.(Link)
		if !linked {
			resolved[column] = value
			continue
		}
		if !validIdentifier(link.Table) || !validIdentifier(link.Column) {
			return nil, fmt.Errorf("vínculo inválido %q.%q", link.Table, link.Column)
		}
		available, found := cache[link]
		if !found {
			rows, err := conn.executor.QueryContext(ctx, "SELECT "+link.Column+" FROM "+link.Table+" ORDER BY "+link.Column)
			if err != nil {
				return nil, fmt.Errorf("consultar vínculo %s.%s: %w", link.Table, link.Column, err)
			}
			for rows.Next() {
				var linkedValue any
				if err := rows.Scan(&linkedValue); err != nil {
					rows.Close()
					return nil, err
				}
				available = append(available, linkedValue)
			}
			if err := rows.Close(); err != nil {
				return nil, err
			}
			if len(available) == 0 {
				return nil, fmt.Errorf("nenhum valor disponível em %s.%s; execute a factory pai primeiro", link.Table, link.Column)
			}
			cache[link] = available
		}
		resolved[column] = available[index%len(available)]
	}
	return resolved, nil
}

func ensureFactoryTable(ctx context.Context, conn registeredConnection) error {
	var statement string
	switch conn.dialect {
	case "oracle":
		statement = `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE flexberry_factories (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			factory_name VARCHAR2(150) NOT NULL, table_name VARCHAR2(150) NOT NULL,
			records_created NUMBER NOT NULL, executed_at TIMESTAMP NOT NULL
		)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`
	case "sqlserver":
		statement = `IF OBJECT_ID(N'flexberry_factories', N'U') IS NULL CREATE TABLE flexberry_factories (
			id BIGINT IDENTITY(1,1) PRIMARY KEY, factory_name NVARCHAR(150) NOT NULL,
			table_name NVARCHAR(150) NOT NULL, records_created INT NOT NULL, executed_at DATETIME2 NOT NULL)`
	case "mysql":
		statement = `CREATE TABLE IF NOT EXISTS flexberry_factories (
			id BIGINT AUTO_INCREMENT PRIMARY KEY, factory_name VARCHAR(150) NOT NULL,
			table_name VARCHAR(150) NOT NULL, records_created INT NOT NULL, executed_at DATETIME NOT NULL)`
	default:
		statement = `CREATE TABLE IF NOT EXISTS flexberry_factories (
			id BIGSERIAL PRIMARY KEY, factory_name VARCHAR(150) NOT NULL,
			table_name VARCHAR(150) NOT NULL, records_created INTEGER NOT NULL, executed_at TIMESTAMP NOT NULL)`
	}
	_, err := conn.executor.ExecContext(ctx, statement)
	return err
}

func insertFactoryData(ctx context.Context, conn registeredConnection, mapping EntityMapping, values map[string]any) error {
	allowed := make(map[string]bool, len(mapping.Fields))
	for _, field := range mapping.Fields {
		allowed[strings.ToLower(field.Column)] = true
	}
	columns := make([]string, 0, len(values))
	normalized := make(map[string]any, len(values))
	for column, value := range values {
		key := strings.ToLower(column)
		if !validIdentifier(column) || !allowed[key] {
			return fmt.Errorf("coluna %q não pertence ao mapping %s", column, mapping.Name)
		}
		columns = append(columns, column)
		normalized[column] = value
	}
	if len(columns) == 0 {
		return fmt.Errorf("factory não gerou campos")
	}
	sort.Strings(columns)
	args := make([]any, len(columns))
	holders := make([]string, len(columns))
	for index, column := range columns {
		args[index] = normalized[column]
		holders[index] = placeholder(conn.dialect, index+1)
	}
	statement := "INSERT INTO " + mapping.Table + " (" + strings.Join(columns, ", ") + ") VALUES (" + strings.Join(holders, ", ") + ")"
	_, err := conn.executor.ExecContext(ctx, statement, args...)
	return err
}

func trackFactory(ctx context.Context, conn registeredConnection, result FactoryResult) error {
	args := []any{result.Name, result.Table, result.Created, result.EndedAt}
	holders := make([]string, len(args))
	for index := range args {
		holders[index] = placeholder(conn.dialect, index+1)
	}
	statement := "INSERT INTO " + FactoryTable +
		" (factory_name, table_name, records_created, executed_at) VALUES (" +
		strings.Join(holders, ", ") + ")"
	_, err := conn.executor.ExecContext(ctx, statement, args...)
	return err
}
