// Package flexberry contains the runtime shared by code generated by the
// Flexberry CLI.
package flexberry

// Version is replaced with the release tag at build time by the release
// workflow. The default is useful for local development builds.
var Version = "0.1.0-alpha.15"
