package migrationgo

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// RefreshCatalog rebuilds dsl.gen.go from the tables already known by the
// catalog and from migrate.CreateTable calls written in migration files.
func RefreshCatalog(folder string) error {
	tables := loadCatalog(filepath.Join(folder, "dsl.gen.go"))
	entries, err := os.ReadDir(folder)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	known := make(map[string]bool, len(tables))
	for _, name := range tables {
		known[name] = true
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "_migration.go") {
			continue
		}
		path := filepath.Join(folder, entry.Name())
		file, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if parseErr != nil {
			return fmt.Errorf("ler tabelas de %s: %w", entry.Name(), parseErr)
		}
		ast.Inspect(file, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			selector, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || identName(selector.X) != "migrate" || selector.Sel.Name != "CreateTable" {
				return true
			}
			literal, ok := call.Args[0].(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return true
			}
			if name, unquoteErr := strconv.Unquote(literal.Value); unquoteErr == nil && name != "" {
				known[name] = true
			}
			return true
		})
	}

	names := make([]string, 0, len(known))
	for name := range known {
		names = append(names, name)
	}
	sort.Strings(names)
	return writeCatalog(filepath.Join(folder, "dsl.gen.go"), names)
}

func writeCatalog(path string, names []string) error {
	var source strings.Builder
	source.WriteString("// Code generated by Flexberry. DO NOT EDIT.\npackage migrations\n\n")
	source.WriteString("import migrate \"github.com/PhelipeViana/flexberry/migration\"\n\n")
	source.WriteString("// Catalog permite que migrations manuais usem alias antes de escolher uma tabela.\n")
	source.WriteString("var Catalog = struct{}{}\n\n")
	source.WriteString("func col(nome string) migrate.Column { return migrate.Col(nome) }\n\n")
	source.WriteString("var alias = struct {\n")
	for _, name := range names {
		fmt.Fprintf(&source, "\t%s migrate.Table\n", tableIdentifier(name))
	}
	source.WriteString("}{\n")
	for _, name := range names {
		fmt.Fprintf(&source, "\t%s: migrate.Table(%q),\n", tableIdentifier(name), name)
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

// WriteCoreCatalog writes the project-owned alias catalog in Flexberry's
// protected core area. Keys are stable aliases and values are physical names.
func WriteCoreCatalog(projectRoot string, aliases map[string]string) error {
	path := filepath.Join(projectRoot, "internal", "flexberry", "core", "migration", "alias", "dsl.gen.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(aliases))
	for alias := range aliases {
		names = append(names, alias)
	}
	sort.Strings(names)
	var source strings.Builder
	source.WriteString("// Code generated by Flexberry. DO NOT EDIT.\npackage alias\n\n")
	source.WriteString("import migrate \"github.com/PhelipeViana/flexberry/migration\"\n\n")
	source.WriteString("// Catalog mantém o import alias válido em migrations manuais ainda vazias.\n")
	source.WriteString("var Catalog = struct{}{}\n\n")
	for _, alias := range names {
		fmt.Fprintf(&source, "var %s = migrate.Table(%q) // physical: %s\n", exportedIdentifier(alias), alias, aliases[alias])
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	// Remove somente o catálogo gerado antigo. Outros arquivos do projeto são
	// preservados e a pasta só é removida quando estiver vazia.
	legacyPath := filepath.Join(projectRoot, "internal", "flexberry", "core", "migration", "table", "dsl.gen.go")
	_ = os.Remove(legacyPath)
	_ = os.Remove(filepath.Dir(legacyPath))
	return nil
}

func exportedIdentifier(value string) string {
	if !strings.ContainsAny(value, "_- .") && value != "" {
		return strings.ToUpper(value[:1]) + value[1:]
	}
	identifier := tableIdentifier(value)
	return strings.ToUpper(identifier[:1]) + identifier[1:]
}

func tableIdentifier(value string) string {
	parts := strings.FieldsFunc(strings.ToLower(value), func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9')
	})
	if len(parts) == 0 {
		return "tabela"
	}
	result := parts[0]
	for _, part := range parts[1:] {
		if part != "" {
			result += strings.ToUpper(part[:1]) + part[1:]
		}
	}
	if result[0] >= '0' && result[0] <= '9' {
		result = "t" + result
	}
	return result
}
