package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"

	"github.com/PhelipeViana/flexberry/internal/config"
	"github.com/PhelipeViana/flexberry/internal/scanner"
)

type File struct {
	Path    string
	Content []byte
}

type Manifest struct {
	Version  int      `json:"version"`
	Entities []string `json:"entities"`
	Sources  []string `json:"sources"`
	Files    []string `json:"files"`
}

func Build(cfg *config.Config, result scanner.Result) ([]File, error) {
	source, err := buildEntities(cfg, result.Entities)
	if err != nil {
		return nil, err
	}
	manifest := Manifest{Version: 1, Sources: append([]string(nil), result.Files...), Files: []string{"entities.gen.go", "manifest.gen.json"}}
	for _, entity := range result.Entities {
		manifest.Entities = append(manifest.Entities, entity.ImportPath+"."+entity.Name)
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("gerar manifest: %w", err)
	}
	data = append(data, '\n')
	return []File{{Path: "entities.gen.go", Content: source}, {Path: "manifest.gen.json", Content: data}}, nil
}

func Write(projectRoot string, cfg *config.Config, files []File) ([]string, error) {
	output := filepath.Clean(filepath.Join(projectRoot, filepath.FromSlash(cfg.Generate.Output)))
	relative, err := filepath.Rel(projectRoot, output)
	if err != nil || relative == "." || relative == ".." || filepath.IsAbs(relative) {
		return nil, fmt.Errorf("generate.output precisa apontar para uma subpasta do projeto")
	}
	if err := os.MkdirAll(output, 0o755); err != nil {
		return nil, fmt.Errorf("criar pasta gerada: %w", err)
	}
	expected := make(map[string]bool)
	var written []string
	for _, file := range files {
		expected[file.Path] = true
		path := filepath.Join(output, file.Path)
		if err := os.WriteFile(path, file.Content, 0o644); err != nil {
			return nil, fmt.Errorf("escrever %s: %w", path, err)
		}
		written = append(written, filepath.ToSlash(filepath.Join(cfg.Generate.Output, file.Path)))
	}
	entries, err := os.ReadDir(output)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		ext := filepath.Ext(entry.Name())
		if !entry.IsDir() && (ext == ".go" || ext == ".json") && !expected[entry.Name()] {
			if err := os.Remove(filepath.Join(output, entry.Name())); err != nil {
				return nil, fmt.Errorf("remover arquivo gerado antigo %s: %w", entry.Name(), err)
			}
		}
	}
	sort.Strings(written)
	return written, nil
}

func buildEntities(cfg *config.Config, entities []scanner.Entity) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Flexberry. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Generate.Package)
	b.WriteString("import (\n\tcore \"github.com/PhelipeViana/flexberry\"\n")
	imported := make(map[string]string)
	for _, entity := range entities {
		imported[entity.ImportPath] = entity.Alias
	}
	var paths []string
	for path := range imported {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&b, "\t%s %s\n", imported[path], strconv.Quote(path))
	}
	b.WriteString(")\n\n")
	for _, entity := range entities {
		fmt.Fprintf(&b, "func %s() core.EntityDefinition[%s.%s] {\n", entity.Function, entity.Alias, entity.Name)
		fmt.Fprintf(&b, "\treturn core.Define[%s.%s](core.EntityMapping{\n", entity.Alias, entity.Name)
		writeMapping(&b, cfg, entity, "\t\t")
		b.WriteString("\t})\n}\n\n")
	}
	b.WriteString("func AllEntities() []core.EntityMapping {\n\treturn []core.EntityMapping{\n")
	for _, entity := range entities {
		fmt.Fprintf(&b, "\t\t%s().Mapping,\n", entity.Function)
	}
	b.WriteString("\t}\n}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatar código gerado: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func writeMapping(b *bytes.Buffer, cfg *config.Config, entity scanner.Entity, indent string) {
	fmt.Fprintf(b, "%sName: %s,\n%sPackage: %s,\n%sImportPath: %s,\n%sTable: %s,\n%sPrimaryKey: %s,\n%sConnection: %s,\n%sDefaultPerPage: %d,\n%sMaxPerPage: %d,\n",
		indent, strconv.Quote(entity.Name), indent, strconv.Quote(entity.Package), indent, strconv.Quote(entity.ImportPath),
		indent, strconv.Quote(entity.Table), indent, strconv.Quote(entity.PrimaryKey), indent, strconv.Quote(entity.Connection),
		indent, cfg.Pagination.DefaultPerPage, indent, cfg.Pagination.MaxPerPage)
	fmt.Fprintf(b, "%sFields: []core.FieldMapping{\n", indent)
	for _, field := range entity.Fields {
		fmt.Fprintf(b, "%s\t{Name: %s, Column: %s, GoType: %s, Nullable: %t, PrimaryKey: %t},\n",
			indent, strconv.Quote(field.Name), strconv.Quote(field.Column), strconv.Quote(field.GoType), field.Nullable, field.PrimaryKey)
	}
	fmt.Fprintf(b, "%s},\n%sRelations: []core.RelationMapping{\n", indent, indent)
	for _, relation := range entity.Relations {
		fmt.Fprintf(b, "%s\t{Name: %s, Type: %s, Kind: %s, ForeignKey: %s},\n",
			indent, strconv.Quote(relation.Name), strconv.Quote(relation.Type), strconv.Quote(relation.Kind), strconv.Quote(relation.ForeignKey))
	}
	fmt.Fprintf(b, "%s},\n", indent)
}
