package sqlimport

import (
	"os"
	"path/filepath"
	"testing"
)

func TestReadPostgresBuildsFinalSchema(t *testing.T) {
	folder := t.TempDir()
	source := `
CREATE TABLE pessoas (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 nome VARCHAR(100) NULL,
 status CHAR(1) DEFAULT 'A' NOT NULL,
 CONSTRAINT pk_pessoas PRIMARY KEY (id),
 CONSTRAINT ck_pessoas_status CHECK (status IN ('A', 'I'))
);
ALTER TABLE pessoas ADD COLUMN criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE pessoas RENAME COLUMN nome TO nome_completo;
CREATE UNIQUE INDEX uk_pessoas_nome ON pessoas (nome_completo);
CREATE OR REPLACE VIEW vw_pessoas AS SELECT id, nome_completo FROM pessoas;
UPDATE pessoas SET status = 'A';`
	if err := os.WriteFile(filepath.Join(folder, "migration.sql"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := ReadPostgres(folder)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Unsupported) != 0 {
		t.Fatalf("não suportados: %#v", result.Unsupported)
	}
	if len(result.Tables) != 1 || len(result.Tables[0].Columns) != 4 {
		t.Fatalf("schema inesperado: %#v", result.Tables)
	}
	if result.Tables[0].byName["nome_completo"] == nil || !result.Tables[0].byName["id"].AutoIncrement {
		t.Fatalf("colunas não reconciliadas: %#v", result.Tables[0])
	}
	if result.Tables[0].byName["id"].Default != "" {
		t.Fatalf("DEFAULT de IDENTITY não pode virar expressão: %#v", result.Tables[0].byName["id"])
	}
	if len(result.Constraints) != 2 || len(result.Indexes) != 1 || len(result.Views) != 1 || result.IgnoredData != 1 {
		t.Fatalf("objetos inesperados: %#v", result)
	}
}

func TestClearGeneratedBaselineRefusesManualFiles(t *testing.T) {
	output := t.TempDir()
	if err := os.WriteFile(filepath.Join(output, "manual.go"), []byte("package migrations\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ClearGeneratedBaseline(output); err == nil {
		t.Fatal("arquivo manual deveria impedir limpeza")
	}
}

func TestWriteBaselineGeneratesOneActionPerFile(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.test/project\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	result := Result{
		Tables:      []*Table{{Name: "pessoas", Columns: []*Column{{Name: "id", Kind: "integer", AutoIncrement: true}}, byName: map[string]*Column{}}},
		Constraints: []Constraint{{Table: "pessoas", Name: "pk_pessoas", Kind: "primary", Columns: []string{"id"}}},
	}
	output := filepath.Join(root, "migrations")
	files, err := WriteBaseline(root, output, "example.test/project", result)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("esperava uma migration, obtido: %#v", files)
	}
	data, err := os.ReadFile(files[0])
	if err != nil {
		t.Fatal(err)
	}
	if string(data) == "" {
		t.Fatal("migration vazia")
	}
}
